services:
  - type: web
    name: abhi-jaat-bot
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: SESSION_ID
        sync: false
      - key: PORT
        value: 3000
